### ISSUE TITLE
Directory missing

### ISSUE THREAD

**Issue by hearts1137** [simeononsecurity/FireFox-STIG-Script#1]
https://github.com/simeononsecurity/FireFox-STIG-Script/blob/752b80d13f30dde547885a2f676fc13fe12450f6/sos-firefoxstig.sh#L12

Line 12 of sos-firefoxstig.sh attempts to copy files from a directory that does not exist. The Config directory is not referenced in the script.

It's unclear which file needs to go where when only mozilla.cfg and autoconfig.js are meant for Linux deployments and there are three copy commands.

**Comment by simeononsecurity** [comment]
Resolved
