### ISSUE TITLE
policies.json file does not exist

### ISSUE THREAD

**Issue by hearts1137** [simeononsecurity/FireFox-STIG-Script#2]
On line 33 the sos-firefoxstig.sh files calls for a copy of policies.json to be put in /lib/firefox/distribution but that file is not included in this repo. Only mozilla.cfg and autoconfig.js are included.

https://github.com/simeononsecurity/FireFox-STIG-Script/blob/6936ee98565478a8c85c1ef4217ef29c86dae767/sos-firefoxstig.sh#L33

**Comment by simeononsecurity** [comment]
#hearts that line is clearly commented out... pending possible future changes
